import type { Metadata } from "next"
import { Fraunces } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar/Navbar"
import Footer from "@/components/Footer/Footer"

const fraunces = Fraunces({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fraunces.className} >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
