import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ApolloRegistry from '@/lib/apollo-registry'
import { Suspense } from 'react'
import LoadingScreen from './_components/LoadingScreen/LoadingScreen'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <ApolloRegistry>
        <Suspense fallback={<LoadingScreen/>}>
          {children}
        </Suspense>
      </ApolloRegistry>
    </body>
  </html>
  )
}
